name = "blog"

workers_dev = false
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2023-09-04"

[dev]
port = 3002

[site]
bucket = "./public"

[build]
command = "bun run build"
